import type { Metadata } from "next";
import "./globals.css";
import "@/app/styles/onlybilwils.css";
import "@/app/styles/continuewatching.css";
import "@/app/styles/herosection.css";
import "@/app/styles/topmovie.css";
import "@/app/font/googlefont.css";
import { PrelineScript } from "@/lib";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <PrelineScript />
        {children}
      </body>
    </html>
  );
}
