import type { Metadata } from "next";
import "./globals.css";
import "@/app/styles/onlybilwils.css";
import "@/app/styles/continuewatching.css";
import "@/app/styles/herosection.css";
import "@/app/styles/moviegenerecarousel.css";
import "@/app/styles/topmovie.css";
import "@/app/styles/Footer.css";
import "@/app/font/googlefont.css";
import "@/app/styles/top10series.css";
import { PrelineScript } from "@/lib";
import { TanstackProvider } from "@/lib"
import StoreProvider from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <TanstackProvider>
            <PrelineScript />
            <div vaul-drawer-wrapper="">{children}</div>
          </TanstackProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
